//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Negocio.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Negocio.Properties.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dd/MM/yyyy.
        /// </summary>
        internal static string DataFormat {
            get {
                return ResourceManager.GetString("DataFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} já votou!.
        /// </summary>
        internal static string MsgJaVotou {
            get {
                return ResourceManager.GetString("MsgJaVotou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Os seguintes restaurantes estão empatados: {0} a votação deverá ser reiniciada!.
        /// </summary>
        internal static string MsgRestauranteEmpatado {
            get {
                return ResourceManager.GetString("MsgRestauranteEmpatado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restaurante escolhido: {0}, com {1} votos.
        /// </summary>
        internal static string MsgRestauranteEscolhido {
            get {
                return ResourceManager.GetString("MsgRestauranteEscolhido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restaurante já escolhido na semana!.
        /// </summary>
        internal static string MsgRestauranteEscolhidoSemana {
            get {
                return ResourceManager.GetString("MsgRestauranteEscolhidoSemana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Votação Encerrada!.
        /// </summary>
        internal static string MsgVotacaoEncerrada {
            get {
                return ResourceManager.GetString("MsgVotacaoEncerrada", resourceCulture);
            }
        }
    }
}
